# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://mohamedallam.tech/"
defaultContentLanguage = "en"
#  hugo --gc --minify -D -b $CF_PAGES_URL
enableRobotsTXT = true
paginate = 10
summaryLength = 0
googleAnalytics = "G-VWFMBMM26W"

[outputs]
  home = ["HTML", "RSS", "JSON"]


[sitemap]
  changefreq = 'Hourly'
  filename = 'sitemap.xml'
